os: linux
dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"
install:
  - pip install poetry
  - poetry install
script: poetry run python -m unittest discover
