os: linux
dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"
matrix:
  allow_failures:
    python: "3.11-dev"  # pytest will need to be upgraded to pass
install:
  - pip install poetry
  - poetry install
script: poetry run python -m unittest discover
