name: lint-and-typecheck
on: [push, pull_request]
jobs:
  lint-and-type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv tool install poethepoet
          uv sync --all-extras

      - name: Format
        run: poe format

      - name: Check spelling
        run: poe spell

      - name: Lint
        run: poe lint

      - name: Typecheck
        run: poe typecheck
