name: lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poethepoet poetry
      - name: Lint (via `poe`)
        run: |
          poetry install
          poe format
          poe codespell
          poe lint
