name: lint-and-type
on: [push, pull_request]
jobs:
  lint-and-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poethepoet poetry
          poetry install
      - name: Lint and typecheck (via `poe`)
        run: |
          poe check
